### ISSUE TITLE
I cannot make it work now

### ISSUE THREAD

**Issue by mangelajo** [hypersleep/rails-on-arm#1]
```
#16 23.76 ________ running 'vpython v8/third_party/depot_tools/update_depot_tools_toggle.py --disable' in '/gn/libv8/vendor'
#16 25.17 ________ running 'vpython v8/build/landmines.py --landmine-scripts v8/tools/get_landmines.py' in '/gn/libv8/vendor'
#16 25.34 ________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clan$
-format.sha1' in '/gn/libv8/vendor'
#16 25.46 ________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' i$
 '/gn/libv8/vendor'
#16 25.58 ________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-js/tests.tar.gz.sha1' in '/gn/l$
bv8/vendor'
#16 26.89 ________ running 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --arch=arm64' in '/gn/libv8/vendor'
#16 28.09 ________ running 'vpython v8/third_party/binutils/download.py' in '/gn/libv8/vendor'
#16 29.41 ________ running 'vpython v8/tools/clang/scripts/update.py' in '/gn/libv8/vendor'
#16 30.67 ________ running 'vpython v8/build/util/lastchange.py -o v8/build/util/LASTCHANGE' in '/gn/libv8/vendor'
#16 30.76 Beginning compilation. This will take some time.
#16 30.96 ERROR at //build/config/BUILDCONFIG.gn:401:1: set_sources_assignment_filter argument must be an empty list.
#16 30.96 set_sources_assignment_filter(sources_assignment_filter)
#16 30.96 ^------------------------------------------------------
#16 31.01 ninja: Entering directory `out.gn/libv8'
#16 31.02 ninja: error: loading 'build.ninja': No such file or directory
#16 31.03 /gn/libv8/ext/libv8/location.rb:41:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/gn/libv8/vendor$
v8/out.gn/libv8/obj/libv8_monolith.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
#16 31.03       from /gn/libv8/ext/libv8/location.rb:40:in `each'
#16 31.03       from /gn/libv8/ext/libv8/location.rb:40:in `verify_installation!'
#16 31.03       from /gn/libv8/ext/libv8/location.rb:26:in `install!'
#16 31.03       from ext/libv8/extconf.rb:7:in `<main>'
#16 31.04 rake aborted!
#16 31.04 Command failed with status (1): [ruby ext/libv8/extconf.rb...]
#16 31.04 /gn/libv8/Rakefile:47:in `block in <top (required)>'
#16 31.04 /usr/local/bin/bundle:30:in `block in <main>'
#16 31.04 /usr/local/bin/bundle:22:in `<main>'
#16 31.04 Tasks: TOP => compile
#16 31.04 (See full trace by running task with --trace)
```

**Comment by hypersleep** [comment]
Hey @mangelajo It seems there is the different issue. Problem now somewhere in v8 code/config. i'll also dig into it soon.

**Comment by odidev** [comment]
@hypersleep, I am working on discourse, which depends on mini_racer and it is further depending on libv8. So I am interested in making it available for arm64. Your efforts are impressive and hopefully will be helpful too.

Please share if you have more findings on this issue.
