### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by supermario** [hypersleep/rails-on-arm#2]
Cloning this repository and running `docker build .` unmodified.

macOS 11.2.1 MacBook Pro (13-inch, M1, 2020)
Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
Docker version 20.10.3, build 48d30b5

```
$ git clone git@github.com:hypersleep/rails-on-arm.git
Cloning into 'rails-on-arm'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 11 (delta 2), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (11/11), 8.41 KiB | 4.21 MiB/s, done.
Resolving deltas: 100% (2/2), done.

# mario ~/dev/test                                                                                                                                                       11:52:45
$ cd rails-on-arm

# mario ~/dev/test/rails-on-arm ± master o                                                                                                                               11:52:46
$ docker build .
[+] Building 27.9s (17/20)
 => [internal] load build definition from Dockerfile                                                                                                                         0.8s
 => => transferring dockerfile: 1.48kB                                                                                                                                       0.1s
 => [internal] load .dockerignore                                                                                                                                            0.4s
 => => transferring context: 2B                                                                                                                                              0.0s
 => [internal] load metadata for docker.io/library/ruby:2.5.8                                                                                                                2.0s
 => [internal] load build context                                                                                                                                           19.0s
 => => transferring context: 103B                                                                                                                                           18.7s
 => [ 1/16] FROM docker.io/library/ruby:2.5.8@sha256:d99439def9ef2349c327ae76665be0d18376f7d9cc4d3a8ddfeb8f970271fdae                                                        0.0s
 => CACHED [ 2/16] RUN apt-get update && apt-get install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget l  0.0s
 => CACHED [ 3/16] RUN git clone https://gn.googlesource.com/gn                                                                                                              0.0s
 => CACHED [ 4/16] WORKDIR /gn                                                                                                                                               0.0s
 => CACHED [ 5/16] RUN sed -i -e "s/-Wl,--icf=all//" build/gen.py && python build/gen.py && ninja -C out                                                                     0.0s
 => CACHED [ 6/16] RUN git clone --recursive git://github.com/rubyjs/libv8.git                                                                                               0.0s
 => CACHED [ 7/16] WORKDIR /gn/libv8                                                                                                                                         0.0s
 => CACHED [ 8/16] RUN bundle install                                                                                                                                        0.0s
 => CACHED [ 9/16] RUN bundle exec rake compile; exit 0                                                                                                                      0.0s
 => CACHED [10/16] RUN wget -q https://github.com/llvm/llvm-project/releases/download/llvmorg-10.0.0/clang+llvm-10.0.0-aarch64-linux-gnu.tar.xz &&     tar xf clang+llvm-10  0.0s
 => CACHED [11/16] RUN mv clang+llvm-10.0.0-aarch64-linux-gnu/* vendor/v8/third_party/llvm-build/Release+Asserts &&     rm -rf clang+llvm-10.0.0-aarch64-linux-gnu.tar.xz c  0.0s
 => CACHED [12/16] RUN cp /gn/out/gn vendor/v8/buildtools/linux64/ &&     cp /usr/bin/ninja vendor/depot_tools/ninja                                                         0.0s
 => ERROR [13/16] RUN bundle exec rake compile &&     bundle exec rake binary &&     gem install /gn/libv8/pkg/libv8-8.4.255.0-aarch64-linux.gem                            24.8s
------
 > [13/16] RUN bundle exec rake compile &&     bundle exec rake binary &&     gem install /gn/libv8/pkg/libv8-8.4.255.0-aarch64-linux.gem:
#16 5.514 ruby ext/libv8/extconf.rb
#16 5.643 creating Makefile
#16 16.93 From https://chromium.googlesource.com/v8/v8
#16 16.93    7705ab1fbb..655ae222dd  master     -> origin/master
#16 18.07 HEAD is now at 1a2073dcfd Version 8.4.255
#16 22.94 ________ running 'vpython v8/third_party/depot_tools/update_depot_tools_toggle.py --disable' in '/gn/libv8/vendor'
#16 23.39 ________ running 'vpython v8/build/landmines.py --landmine-scripts v8/tools/get_landmines.py' in '/gn/libv8/vendor'
#16 23.42 ________ running 'download_from_google_storage --no_resume --platform=linux* --no_auth --bucket chromium-clang-format -s v8/buildtools/linux64/clang-format.sha1' in '/gn/libv8/vendor'
#16 23.45 ________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-spec-tests/tests.tar.gz.sha1' in '/gn/libv8/vendor'
#16 23.47 ________ running 'download_from_google_storage --no_resume --no_auth -u --bucket v8-wasm-spec-tests -s v8/test/wasm-js/tests.tar.gz.sha1' in '/gn/libv8/vendor'
#16 23.58 ________ running 'vpython v8/build/linux/sysroot_scripts/install-sysroot.py --arch=arm64' in '/gn/libv8/vendor'
#16 23.68 ________ running 'vpython v8/third_party/binutils/download.py' in '/gn/libv8/vendor'
#16 23.79 ________ running 'vpython v8/tools/clang/scripts/update.py' in '/gn/libv8/vendor'
#16 23.89 ________ running 'vpython v8/build/util/lastchange.py -o v8/build/util/LASTCHANGE' in '/gn/libv8/vendor'
#16 23.92 Beginning compilation. This will take some time.
#16 23.95 ERROR at //build/config/BUILDCONFIG.gn:401:1: Unknown function.
#16 23.95 set_sources_assignment_filter(sources_assignment_filter)
#16 23.95 ^----------------------------
#16 23.95 ninja: Entering directory `out.gn/libv8'
#16 23.95 ninja: error: loading 'build.ninja': No such file or directory
#16 23.96 /gn/libv8/ext/libv8/location.rb:41:in `block in verify_installation!': libv8 did not install properly, expected binary v8 archive '/gn/libv8/vendor/v8/out.gn/libv8/obj/libv8_monolith.a'to exist, but it was not found (Libv8::Location::Vendor::ArchiveNotFound)
#16 23.96 	from /gn/libv8/ext/libv8/location.rb:40:in `each'
#16 23.96 	from /gn/libv8/ext/libv8/location.rb:40:in `verify_installation!'
#16 23.96 	from /gn/libv8/ext/libv8/location.rb:26:in `install!'
#16 23.96 	from ext/libv8/extconf.rb:7:in `<main>'
#16 23.97 rake aborted!
#16 23.97 Command failed with status (1): [ruby ext/libv8/extconf.rb...]
#16 23.97 /gn/libv8/Rakefile:47:in `block in <top (required)>'
#16 23.97 /usr/local/bin/bundle:30:in `block in <main>'
#16 23.97 /usr/local/bin/bundle:22:in `<main>'
#16 23.97 Tasks: TOP => compile
#16 23.97 (See full trace by running task with --trace)
------
executor failed running [/bin/sh -c bundle exec rake compile &&     bundle exec rake binary &&     gem install /gn/libv8/pkg/libv8-8.4.255.0-aarch64-linux.gem]: exit code: 1
```

**Comment by niko-zvt** [comment]
Cloning this repository and running `docker build .` unmodified.

macOS 14.0 23A344. MacBook Pro (M2 Pro)
Darwin Kernel Version 23.0.0
Docker version 24.0.2, build cb74dfc

```
 => ERROR [ 5/16] RUN sed -i -e "s/-Wl,--icf=all//" build/gen.py && python build/gen.py && ninja -C out                     0.4s
------
 > [ 5/16] RUN sed -i -e "s/-Wl,--icf=all//" build/gen.py && python build/gen.py && ninja -C out:
0.333 ninja: Entering directory `out'
0.382 [1/287] CXX src/base/files/file_enumerator.o
0.382 FAILED: src/base/files/file_enumerator.o
0.382 clang++ -MMD -MF src/base/files/file_enumerator.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -Wrange-loop-analysis -Wextra-semi-stmt -c ../src/base/files/file_enumerator.cc -o src/base/files/file_enumerator.o
0.382 error: unknown warning option '-Wextra-semi-stmt'; did you mean '-Wextra-semi'? [-Werror,-Wunknown-warning-option]
0.383 [2/287] CXX src/base/environment.o
0.383 FAILED: src/base/environment.o
0.383 clang++ -MMD -MF src/base/environment.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -Wrange-loop-analysis -Wextra-semi-stmt -c ../src/base/environment.cc -o src/base/environment.o
0.383 error: unknown warning option '-Wextra-semi-stmt'; did you mean '-Wextra-semi'? [-Werror,-Wunknown-warning-option]
0.384 [3/287] CXX src/base/command_line.o
0.384 FAILED: src/base/command_line.o
0.384 clang++ -MMD -MF src/base/command_line.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -Wrange-loop-analysis -Wextra-semi-stmt -c ../src/base/command_line.cc -o src/base/command_line.o
0.384 error: unknown warning option '-Wextra-semi-stmt'; did you mean '-Wextra-semi'? [-Werror,-Wunknown-warning-option]
0.384 [4/287] CXX src/base/files/file.o
0.384 FAILED: src/base/files/file.o
0.384 clang++ -MMD -MF src/base/files/file.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -Wrange-loop-analysis -Wextra-semi-stmt -c ../src/base/files/file.cc -o src/base/files/file.o
0.384 error: unknown warning option '-Wextra-semi-stmt'; did you mean '-Wextra-semi'? [-Werror,-Wunknown-warning-option]
0.390 [5/287] CXX src/base/files/file_path.o
0.390 FAILED: src/base/files/file_path.o
0.390 clang++ -MMD -MF src/base/files/file_path.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -Wrange-loop-analysis -Wextra-semi-stmt -c ../src/base/files/file_path.cc -o src/base/files/file_path.o
0.390 error: unknown warning option '-Wextra-semi-stmt'; did you mean '-Wextra-semi'? [-Werror,-Wunknown-warning-option]
0.390 [6/287] CXX src/base/files/scoped_file.o
0.390 FAILED: src/base/files/scoped_file.o
0.390 clang++ -MMD -MF src/base/files/scoped_file.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -Wrange-loop-analysis -Wextra-semi-stmt -c ../src/base/files/scoped_file.cc -o src/base/files/scoped_file.o
0.390 error: unknown warning option '-Wextra-semi-stmt'; did you mean '-Wextra-semi'? [-Werror,-Wunknown-warning-option]
0.390 [7/287] CXX src/base/files/file_path_constants.o
0.390 FAILED: src/base/files/file_path_constants.o
0.390 clang++ -MMD -MF src/base/files/file_path_constants.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -Wrange-loop-analysis -Wextra-semi-stmt -c ../src/base/files/file_path_constants.cc -o src/base/files/file_path_constants.o
0.390 error: unknown warning option '-Wextra-semi-stmt'; did you mean '-Wextra-semi'? [-Werror,-Wunknown-warning-option]
0.392 [8/287] CXX src/base/files/file_util.o
0.392 FAILED: src/base/files/file_util.o
0.392 clang++ -MMD -MF src/base/files/file_util.o.d -I../src -I. -DNDEBUG -O3 -fdata-sections -ffunction-sections -Werror -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -pthread -pipe -fno-exceptions -fno-rtti -fdiagnostics-color -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wundef -std=c++17 -Wrange-loop-analysis -Wextra-semi-stmt -c ../src/base/files/file_util.cc -o src/base/files/file_util.o
0.392 error: unknown warning option '-Wextra-semi-stmt'; did you mean '-Wextra-semi'? [-Werror,-Wunknown-warning-option]
0.392 ninja: build stopped: subcommand failed.
------
Dockerfile:10
--------------------
   8 |     RUN git clone https://gn.googlesource.com/gn
   9 |     WORKDIR /gn
  10 | >>> RUN sed -i -e "s/-Wl,--icf=all//" build/gen.py && python build/gen.py && ninja -C out
  11 |
  12 |     RUN git clone --recursive git://github.com/rubyjs/libv8.git
--------------------
ERROR: failed to solve: process "/bin/sh -c sed -i -e \"s/-Wl,--icf=all//\" build/gen.py && python build/gen.py && ninja -C out" did not complete successfully: exit code: 1
```

**Comment by tisba** [comment]
This repo is totally outdated. There is nothing special needed for a long time anymore. Please don't use hopelessly outdated Ruby 2.5.8 anymore (as in this repos Dockerfile).

**Comment by supermario** [comment]
Okie dokie.
